name: Resource group
description: Deploys a resource group

inputs:
  resource-group-name:
    description: Name of the resource group
    required: true
  resource-group-location:
    description: Location of the resource group
    required: true
outputs:
  resource-group-unique-string:
    description: The unique string for this resource group ID (lower-case)
    value: ${{ steps.deploy-resource-group.outputs.resourceGroupUniqueString }}

runs:
  using: composite
  steps:
    - name: Set current date as environment variable
      run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      shell: bash

    - name: Deploy resource group
      id: deploy-resource-group
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{env.NOW}}-rg-${{inputs.resource-group-name}}
        scope: subscription
        region: ${{ inputs.resource-group-location }}
        template: ./infrastructure/resource-group.bicep
        parameters: >-
          resourceGroupName=${{ inputs.resource-group-name }}
          resourceGroupLocation=${{ inputs.resource-group-location }}

