schema:
  - src/features/**/*.graphql
  - src/schema/**/*.graphql
documents:
  - 'src/features/**/*.{ts,tsx}'
extensions:
  codegen:
    generates:
      ./src/generated/:
        preset: 'client-preset'
        plugins:
          - typescript-resolvers:
              useIndexSignature: true
              contextType: ../context#GraphQLContext
              mappers:
                Template: ../features/templates/entities/template-entity#TemplateEntity
        config:
          defaultScalarType: unknown
          scalars:
            # add types for any used scalars here
            LocalDate: string
            EmailAddress: string
            PositiveInt: number
            PositiveFloat: number
            URL: string
            DateTime: Date
            Locale: string
            HexColorCode: string
