schema:
  - src/features/**/*.graphql
  - src/schema/**/*.graphql
documents:
  - 'src/features/**/*.{ts,tsx}'
extensions:
  codegen:
    generates:
      ./src/generated/:
        preset: 'client-preset'
        plugins:
          - typescript-resolvers:
              useIndexSignature: true
              contextType: ../context#GraphQLContext
              resolverTypeWrapperSignature: 'Promise<T | Error> | T | Error'
        config:
          scalars:
            # add types for any used scalars here
            LocalDate: string
            EmailAddress: string
            PositiveInt: number
            PositiveFloat: number
            URL: string

