schema:
  - src/background-jobs/**/*.graphql
  - src/features/**/*.graphql
  - src/schema/**/*.graphql
documents:
  - 'src/**/*.{ts,tsx}'
extensions:
  codegen:
    generates:
      ./src/generated/:
        preset: 'client-preset'
        presetConfig:
          fragmentMasking: false
        plugins:
          - typescript-resolvers:
              contextType: ../context#GraphQLContext
              mappers:
                Template: ../features/templates/entities/template-entity#TemplateEntity
                Contract: ../features/contracts/entities/contract-entity#ContractEntity
                User: ../features/users/entities/user-entity#UserEntity
                Issuance: ../features/issuance/entities/issuance-entity#IssuanceEntity
                Presentation: ../features/presentation/entities/presentation-entity#PresentationEntity
                PresentationFlow: ../features/presentation-flow/entities/presentation-flow-entity#PresentationFlowEntity
                PresentationFlowTemplate: ../features/presentation-flow/entities/presentation-flow-template-entity#PresentationFlowTemplateEntity
                Identity: ../features/identity/entities/identity-entity#IdentityEntity
                IdentityStore: ../features/identity-store/entities/identity-store-entity#IdentityStoreEntity
                Partner: ../features/partners/entities/partner-entity#PartnerEntity
                AsyncIssuanceRequest: ../features/async-issuance/entities/async-issuance-entity#AsyncIssuanceEntity
                Communication: ../features/communication/entities/communication-entity#CommunicationEntity
                OidcClient: ../features/oidc-provider/entities/oidc-client-entity#OidcClientEntity
                OidcResource: ../features/oidc-provider/entities/oidc-resource-entity#OidcResourceEntity
                OidcClientResource: ../features/oidc-provider/entities/oidc-client-resource-entity#OidcClientResourceEntity
                OidcClaimMapping: ../features/oidc-provider/entities/oidc-claim-mapping-entity#OidcClaimMappingEntity
                OidcIdentityResolver: ../features/oidc-provider/entities/oidc-identity-resolver-entity#OidcIdentityResolverEntity
                Branding: ../features/branding/entities/branding-entity#BrandingEntity
                Wallet: ../features/wallet/entities/wallet-entity#WalletEntity
                ApplicationLabelConfig: ../features/instance-configs/entities/application-label-config-entity#ApplicationLabelConfigEntity
                CorsOriginConfig: ../features/instance-configs/entities/cors-origins-config-entity#CorsOriginConfigEntity
                MicrosoftEntraTemporaryAccessPassIssuance: ../features/microsoft-entra-temporary-access-pass-issuance/entities/microsoft-entra-temporary-access-pass-issuance-entity#MicrosoftEntraTemporaryAccessPassIssuanceEntity
                MicrosoftEntraTemporaryAccessPassIssuanceConfiguration: ../features/microsoft-entra-temporary-access-pass-issuance/entities/microsoft-entra-temporary-access-pass-issuance-configuration-entity#MicrosoftEntraTemporaryAccessPassIssuanceConfigurationEntity
                CredentialRecord: ../features/credential-record/queries/find-credential-records-query#CredentialRecordRow
        config:
          strictScalars: true
          scalars:
            # add types for any used scalars here and in schema.ts
            PositiveInt: number
            NonNegativeInt: number
            PositiveFloat: number
            DataURL: string
            URL: string
            DateTime: Date
            Locale: string
            HexColorCode: string
            Void: null | undefined | void
            JSON: unknown
            JSONObject: Record<string, unknown>
            EmailAddress: string
            UUID: string
            Markdown: string
      ./src/generated/schema.json:
        sort: true
        plugins:
          - introspection
        config:
          minify: true
      ./src/generated/schema.graphql:
        plugins:
          - schema-ast
