version: '3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 7o}R~=XA1jmz!-aHQ^pA
  redis:
    image: redis:7-alpine
    container_name: cache
    restart: always
    ports:
      - 6380:6379
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    # just run the blob service for now
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    restart: always
    ports:
      - 10000:10000
