services:
- type: web
  name: vo.docs
  runtime: static
  repo: https://github.com/VerifiedOrchestration/verified-orchestration-api
  branch: main
  buildCommand: cd ./docs-site && npm install && npm run generate-graphql-docs &&
    npm run build
  staticPublishPath: build
  autoDeployTrigger: commit
  buildFilter:
    paths:
    - docs-site/**
    - src/generated/schema.json
version: "1"
