FROM node:alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY tsconfig.json docusaurus.config.js babel.config.js sidebars.js ./
COPY static ./static/
COPY docs ./docs/
COPY src ./src/
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--no-open"]