FROM node:alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY tsconfig.json docusaurus.config.js babel.config.js sidebarsDocumentation.js sidebarsApiReference.js ./
COPY docs ./docs/
COPY api-reference ./api-reference/
COPY release-notes ./release-notes/
COPY static ./static/
COPY src ./src/
RUN mkdir blog
COPY scripts ./scripts/
CMD ["npm", "run", "start:dev"]
