// These configurations values are for the DEV environment.
@PLATFORM_TENANT_ID = 5c14bb50-7602-4c0d-b785-5dee865e4665
@BASE_URL=https://verifiedid.did.msidentity.com
@APP_SCOPE=6a8b4b39-c021-437c-b060-5a14a3fd65f3/.default
@API_CLIENT_ID=f24dc8de-66da-4b8b-928b-be4c6657d1cc
@API_CLIENT_SECRET={{$dotenv API_CLIENT_SECRET}}
@VID_AUTHORITY_ID=5db71aa7-41ed-9199-40f5-54c789d7d5a4

###
# Authenticate as a client application
# @name login
POST https://login.microsoftonline.com/{{PLATFORM_TENANT_ID}}/oauth2/v2.0/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{API_CLIENT_ID}}
&client_secret={{API_CLIENT_SECRET}}
&grant_type=client_credentials
&scope={{APP_SCOPE}}

###
# List Contracts
# @name listContracts
@BEARER_TOKEN = {{login.response.body.access_token}}
@TOP = 50
@SKIP = 50

GET {{BASE_URL}}/v1.0/verifiableCredentials/authorities/{{VID_AUTHORITY_ID}}/contracts?top={{TOP}}&skip={{SKIP}} HTTP/1.1
Authorization: Bearer {{BEARER_TOKEN}}

###
# Get Contract (uses the first id from the List Contracts response)
# @name get-contract
@BEARER_TOKEN = {{login.response.body.access_token}}
@CONTRACT_ID = {{listContracts.response.body.value[0].id}}

GET {{BASE_URL}}/v1.0/verifiableCredentials/authorities/{{VID_AUTHORITY_ID}}/contracts/{{CONTRACT_ID}} HTTP/1.1
Authorization: Bearer {{BEARER_TOKEN}}

