name: Remove SQL firewall rule
description: Removes a SQL firewall rule by name

inputs:
  azure-client-id:
    description: App ID of the deployment app registration
    required: true
  azure-tenant-id:
    description: ID of the target Azure AD tenant
    required: true
  azure-subscription-id:
    description: ID of the target Azure subscription
    required: true
  resource-group-name:
    description: Name of the resource group
    required: true
  sql-server-name:
    description: Name of the SQL Server
    required: true
  rule-name:
    description: Name of the firewall rule to remove
    required: true

runs:
  using: composite
  steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
        enable-AzPSSession: true

    - name: Set current date as environment variable
      run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      shell: bash

    - name: Remove SQL firewall rule
      id: remove-sql-firewall-rule
      shell: pwsh
      run: >-
        ./infrastructure/scripts/sql-firewall-rule-remove.ps1
        -SqlServerName '${{ inputs.sql-server-name }}'
        -ResourceGroupName '${{ inputs.resource-group-name }}'
        -RuleName '${{ inputs.rule-name }}'

