name: SQL Server setup
description: Sets up a SQL Server after creation

inputs:
  azure-client-id:
    description: App ID of the deployment app registration
    required: true
  sql-server-name:
    description: Name of the SQL Server
    required: true

runs:
  using: composite
  steps:
    - name: 'Create SQL server setup script'
      shell: bash
      run: |
        appName=`az ad app list --app-id ${{ inputs.azure-client-id }} --query [].displayName --output tsv`
        newPwd=`uuidgen`
        echo "IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE [name] = '${appName}')" >> user-setup.sql
        echo "BEGIN" >> user-setup.sql
        echo "  CREATE LOGIN [${appName}] FROM EXTERNAL PROVIDER;" >> user-setup.sql
        echo "  CREATE USER [${appName}] FOR LOGIN [${appName}];" >> user-setup.sql
        echo "  ALTER ROLE [dbmanager] ADD MEMBER [${appName}];" >> user-setup.sql
        echo "END" >> user-setup.sql
        echo "IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE [name] = 'DisabledLogin')" >> user-setup.sql
        echo "BEGIN" >> user-setup.sql
        echo "  CREATE LOGIN [DisabledLogin] WITH PASSWORD = '${newPwd}';" >> user-setup.sql
        echo "  ALTER LOGIN [DisabledLogin] DISABLE;" >> user-setup.sql
        echo "END" >> user-setup.sql

    - name: 'Run SQL server setup script'
      uses: azure/sql-action@v2.2.1
      with:
        connection-string: Server=${{ inputs.sql-server-name }}.database.windows.net;Initial Catalog=master;Authentication=Active Directory Default; Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
        path: 'user-setup.sql'
