name: Shared infrastructure
description: Deploys shared infrastructure

inputs:
  azure-client-id:
    description: App ID of the deployment app registration
    required: true
  azure-tenant-id:
    description: ID of the target Azure AD tenant
    required: true
  azure-subscription-id:
    description: ID of the target Azure subscription
    required: true
  infra-environment:
    description: The hosting environment, either 'nonprd' or 'prd'
    required: true
  resource-group-name:
    description: Name of the resource group to deploy resources to
    required: true

outputs:
  sql-server-1-name:
    description: Name of the deployed SQL Server
    value: ${{ steps.deploy-shared-infrastructure.outputs.sqlServer1Name }}
  app-service-plan-1-id:
    description: ID of the deployed App Service Plan
    value: ${{ steps.deploy-shared-infrastructure.outputs.appServicePlan1Id }}

runs:
  using: composite
  steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Set current date as environment variable
      run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      shell: bash

    - name: Shared infrastructure
      id: deploy-shared-infrastructure
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{env.NOW}}-shared-infra-github-actions
        resourceGroupName: ${{ inputs.resource-group-name }}
        template: ./infrastructure/shared.bicep
        parameters: ./infrastructure/parameters/shared.${{ inputs.infra-environment }}.bicepparam

    - name: 'Create database service principal setup scripts'
      shell: bash
      run: |
        appName=`az ad app list --app-id ${{ inputs.azure-client-id }} --query [].displayName --output tsv`
        echo "IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE [name] = '${appName}')" >> deployer-setup.sql
        echo "BEGIN" >> deployer-setup.sql
        echo "  CREATE USER [${appName}] FROM EXTERNAL PROVIDER;" >> deployer-setup.sql
        echo "  ALTER ROLE [dbmanager] ADD MEMBER [${appName}];" >> deployer-setup.sql
        echo "END" >> deployer-setup.sql
        cat deployer-setup.sql

    - name: 'Set up deployer service principal database roles'
      uses: azure/sql-action@v2.2.1
      with:
        connection-string: Server=${{ steps.deploy-shared-infrastructure.outputs.sqlServer1Name }}.database.windows.net;Initial Catalog=master;Authentication=Active Directory Default; Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
        path: 'deployer-setup.sql'

    - name: Output ${{ inputs.infra-environment }} shared infra variable values
      shell: bash
      run: |
          echo "SQL_SERVER_NAME=${{ steps.deploy-shared-infrastructure.outputs.sqlServer1Name }}"
          echo "APP_SERVICE_PLAN_ID=${{ steps.deploy-shared-infrastructure.outputs.appServicePlan1Id }}"

