name: Deployment
description: Deploys the application to an environment

inputs:
  azure-client-id:
    description: App ID of the deployment app registration
    required: true
  azure-service-principal-object-id:
    description: Object ID of the deployment service principal
    required: true
  azure-tenant-id:
    description: ID of the target Azure AD tenant
    required: true
  azure-subscription-id:
    description: ID of the target Azure subscription
    required: true
  environment:
    description: Name of the environment
    required: true
  resource-group-name:
    description: Name of the resource group to deploy resources to
    required: true

  sql-instance-name:
    description: Name of the Azure SQL instance
    required: true
  sql-instance-aad-administrator-name:
    description: Name of the Azure SQL administrators principal
    required: true
  sql-instance-aad-administrator-object-id:
    description: Object ID of the Azure SQL administrators principal
    required: true
  sql-database-sku:
    description: SKU of the Azure SQL database
    required: true

  redis-cache-name:
    description: Name of the Azure Redis Cache
    required: true
  redis-cache-sku:
    description: SKU of the Azure Redis Cache
    required: true
  redis-cache-family:
    description: Family of the Azure Redis Cache
    required: true
  redis-cache-capacity:
    description: Capacity of the Azure Redis Cache
    required: true

  app-service-plan-sku:
    description: SKU of the App Service Plan
    required: true
  api-app-service-name:
    description: Name of the API App Service
    required: true
  migrations-function-app-name:
    description: Name of the migrations Functions app
    required: true
  migrations-app-client-id:
    description: Client ID of the migrations app registration in Azure AD
    required: true

  api-cookie-secret:
    description: Cookie secret used by the cookie-session Express middleware
    required: true
  api-client-secret:
    description: Client secret of the API app registration in Azure AD
    required: true
  ui-client-secret:
    description: Client secret of the UI app registration in Azure AD
    required: true
  vid-callback-client-secret:
    description: Client secret of the VID callback app registration in Azure AD
    required: true
  limited-access-client-secret:
    description: "The client secret of the limited access client in Azure AD"
    required: true
  limited-access-secret:
    description: "The secret for limited access client data keys"
    required: true
  sendgrid-api-key:
    description: API key for SendGrid
    required: true

  migrations-app-version:
    description: Version returned by the GetVersion function of the migrations Function app
    required: true

  docs-site-artifact-name:
    description: Environment specific artifact name for docs site
    required: true
  docs-site-client-id:
    description: Client id of the docs site app registration in Azure AD
    required: true
  docs-site-client-secret:
    description: Client secret of the docs site app registration in Azure AD
    required: true

outputs:
  api-url:
    description: URL of the deployed API
    value: ${{ steps.deploy-api.outputs.webapp-url }}

runs:
  using: composite
  steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Set current date as environment variable
      run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      shell: bash

    - name: Disable AAD-only auth on the Azure SQL instance
      shell: pwsh
      run: >-
        ./infrastructure/scripts/disable-sql-aad-only-auth.ps1
        -ResourceGroupName '${{ inputs.resource-group-name }}'
        -AzureSqlInstanceName '${{ inputs.sql-instance-name }}'

    - name: Deploy infrastructure
      id: deploy-infrastructure
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{env.NOW}}-api-github-actions
        resourceGroupName: ${{ inputs.resource-group-name }}
        template: ./infrastructure/template.bicep
        parameters: >-
          environment=${{ inputs.environment }}
          servicePrincipalObjectId=${{ inputs.azure-service-principal-object-id }}
          sqlInstanceAadAdministratorName="${{ inputs.sql-instance-aad-administrator-name }}"
          sqlInstanceAadAdministratorObjectId=${{ inputs.sql-instance-aad-administrator-object-id }}
          sqlDatabaseName=VerifiedOrchestration
          sqlDatabaseSku=${{ inputs.sql-database-sku }}
          appServicePlanSku=${{ inputs.app-service-plan-sku }}
          apiCookieSecret=${{ inputs.api-cookie-secret }}
          apiClientSecret=${{ inputs.api-client-secret }}
          uiClientSecret=${{ inputs.ui-client-secret }}
          migrationsAppClientId=${{ inputs.migrations-app-client-id }}
          deploymentAppClientId=${{ inputs.azure-client-id }}
          b2cGraphClientSecret=${{ inputs.b2c-graph-client-secret }}
          vidCallbackClientSecret=${{ inputs.vid-callback-client-secret }}
          limitedAccessClientSecret=${{ inputs.limited-access-client-secret }}
          limitedAccessSecret=${{ inputs.limited-access-secret }}
          sendgridApiKey=${{ inputs.sendgrid-api-key }}
          migrationsAppVersion=${{ inputs.migrations-app-version }}
          redisCacheName=${{ inputs.redis-cache-name }}
          redisCacheSKU=${{ inputs.redis-cache-sku }}
          redisCacheFamily=${{ inputs.redis-cache-family }}
          redisCacheCapacity=${{ inputs.redis-cache-capacity }}
          docsSiteClientId=${{ inputs.docs-site-client-id }}
          docsSiteClientSecret=${{ inputs.docs-site-client-secret }}

    - name: Log in to Azure again after potential long deployment
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Enable AAD-only auth on the Azure SQL instance
      shell: pwsh
      run: >-
        ./infrastructure/scripts/enable-sql-aad-only-auth.ps1
        -ResourceGroupName '${{ inputs.resource-group-name }}'
        -AzureSqlInstanceName '${{ inputs.sql-instance-name }}'

    - name: Deploy migrations Functions app
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.migrations-function-app-name }}
        package: migrations-function/migrations-function.zip

    - name: Restart migrations Functions app
      shell: pwsh
      id: migrationFunctionsRestart
      run: |
        $value = '${{ inputs.migrations-function-app-name }}'
        $resourceGroup = '${{ inputs.resource-group-name }}'
        az functionapp restart --name $value --resource-group $resourceGroup

    - name: Run database migrations
      shell: pwsh
      run: >-
        ./infrastructure/scripts/invoke-database-migrations-function.ps1
        -FunctionAppName '${{ inputs.migrations-function-app-name }}'
        -MigrationsAppClientId '${{ inputs.migrations-app-client-id }}'
        -ExpectedVersion '${{ inputs.migrations-app-version }}'

    - name: Deploy API to App Service
      id: deploy-api
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.api-app-service-name }}
        package: api/api.zip

    - name: Get Static Web Apps deployment token for docs-site
      shell: bash
      run: |
        DOCS_SITE_WEB_APPS_TOKEN=$(az staticwebapp secrets list --name ${{ steps.deploy-infrastructure.outputs.docsSiteWebAppName }} --query "properties.apiKey" --output tsv)
        echo "::add-mask::$DOCS_SITE_WEB_APPS_TOKEN"
        echo DOCS_SITE_WEB_APPS_TOKEN=$DOCS_SITE_WEB_APPS_TOKEN >> $GITHUB_ENV

    - name: Unzip docs site content
      shell: bash
      run: |
        unzip -qq ./${{ inputs.docs-site-artifact-name }}/docs-site.zip -d ./${{ inputs.docs-site-artifact-name }}/build

    - name: Deploy docs site
      id: deploy-docs-site
      uses: Azure/static-web-apps-deploy@v1
      with:
        action: upload
        azure_static_web_apps_api_token: ${{ env.DOCS_SITE_WEB_APPS_TOKEN }}
        skip_app_build: true
        skip_api_build: true
        output_location: ''
        app_location: ./${{ inputs.docs-site-artifact-name }}/build
