name: Deployment
description: Deploys the application to an environment

inputs:
  azure-client-id:
    description: App ID of the deployment app registration
    required: true
  azure-service-principal-object-id:
    description: Object ID of the deployment service principal
    required: true
  azure-tenant-id:
    description: ID of the target Azure AD tenant
    required: true
  azure-subscription-id:
    description: ID of the target Azure subscription
    required: true
  environment:
    description: Name of the environment
    required: true
  resource-group-name:
    description: Name of the resource group to deploy resources to
    required: true
  sql-instance-name:
    description: Name of the Azure SQL instance
    required: true
  sql-instance-aad-administrator-name:
    description: Name of the Azure SQL administrators principal
    required: true
  sql-instance-aad-administrator-object-id:
    description: Object ID of the Azure SQL administrators principal
    required: true
  sql-database-sku:
    description: SKU of the Azure SQL database
    required: true
  app-service-plan-sku:
    description: SKU of the App Service Plan
    required: true
  api-app-service-name:
    description: Name of the API App Service
    required: true
  migrations-function-app-name:
    description: Name of the migrations Functions app
    required: true
  migrations-app-client-id:
    description: Client ID of the migrations app registration in Azure AD
    required: true
  api-cookie-secret:
    description: Cookie secret used by the cookie-session Express middleware
    required: true
  api-client-secret:
    description: Client secret of the API app registration in Azure AD
    required: true
outputs:
  api-url:
    description: URL of the deployed API
    value: ${{ steps.deploy-api.outputs.webapp-url }}

runs:
  using: composite
  steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Set current date as environment variable
      run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      shell: bash

    - name: Disable AAD-only auth on the Azure SQL instance
      shell: pwsh
      run: >-
        ./infrastructure/scripts/disable-sql-aad-only-auth.ps1
        -ResourceGroupName '${{ inputs.resource-group-name }}'
        -AzureSqlInstanceName '${{ inputs.sql-instance-name }}'

    - name: Deploy infrastructure
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{env.NOW}}-api-github-actions
        resourceGroupName: ${{ inputs.resource-group-name }}
        template: ./infrastructure/template.bicep
        parameters: >-
          environment=${{ inputs.environment }}
          servicePrincipalObjectId=${{ inputs.azure-service-principal-object-id }}
          sqlInstanceAadAdministratorName="${{ inputs.sql-instance-aad-administrator-name }}"
          sqlInstanceAadAdministratorObjectId=${{ inputs.sql-instance-aad-administrator-object-id }}
          sqlDatabaseName=VerifiedOrchestration
          sqlDatabaseSku=${{ inputs.sql-database-sku }}
          appServicePlanSku=${{ inputs.app-service-plan-sku }}
          apiCookieSecret=${{ inputs.api-cookie-secret }}
          apiClientSecret=${{ inputs.api-client-secret }}
          migrationsAppClientId=${{ inputs.migrations-app-client-id }}
          deploymentAppClientId=${{ inputs.azure-client-id }}

    - name: Enable AAD-only auth on the Azure SQL instance
      shell: pwsh
      run: >-
        ./infrastructure/scripts/enable-sql-aad-only-auth.ps1
        -ResourceGroupName '${{ inputs.resource-group-name }}'
        -AzureSqlInstanceName '${{ inputs.sql-instance-name }}'

    - name: Deploy migrations Functions app
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.migrations-function-app-name }}
        package: migrations-function/migrations-function.zip

    - name: Run database migrations
      shell: pwsh
      run: >-
        ./infrastructure/scripts/invoke-database-migrations-function.ps1
        -FunctionAppName '${{ inputs.migrations-function-app-name }}'
        -FunctionName 'RunDatabaseMigrations'
        -MigrationsAppClientId '${{ inputs.migrations-app-client-id }}'

    - name: Deploy API to App Service
      id: deploy-api
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.api-app-service-name }}
        package: api/api.zip
