name: Deploy instance (prod)
# DO NOT CHANGE THE FORMAT OF THE `run-name` FIELD
# - it follows a standard pattern across all components
# - it is used to derive the instance, component and environment
run-name: Deploy ${{ inputs.instance }} api to prod

on:
  workflow_dispatch:
    inputs:
      instance:
        description: 'The instance to deploy'
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ inputs.instance }}
  cancel-in-progress: true

jobs:

  build-api:
    name: Build API
    uses: makerxstudio/shared-config/.github/workflows/node-build-zip.yml@main
    with:
      node-version: 22.x
      artifact-name: api

  build-migrations-package:
    name: Build Migrations Package
    uses: makerxstudio/shared-config/.github/workflows/node-build-zip.yml@main
    with:
      node-version: 22.x
      working-directory: ./migrate-db
      artifact-name: migrations-package



  upload-other-artifacts:
    name: Upload other artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Upload infrastructure artifact
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure
          path: ./infrastructure
          if-no-files-found: error

      - name: Upload github-actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-actions
          path: ./.github/actions
          if-no-files-found: error

  deploy:
    name: Deploy to prod
    runs-on: vo-saas-vnet-runner-prod
    permissions:
      id-token: write
    needs:
      - build-api
      - build-migrations-package
      - upload-other-artifacts
    environment:
      name: ${{ inputs.instance }}
      url: https://${{ inputs.instance }}.api.verifiedorchestration.com
    steps:
      - name: Set variables
        id: set-vars
        shell: bash
        run: |
          instance=${{ inputs.instance }}
          echo "resource-group-name=vo-${instance/./-}-instance" >> $GITHUB_ENV
          echo "resource-prefix=vo-${instance/./-}" >> $GITHUB_ENV
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.PROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.PROD_AZURE_TENANT_ID }}
          subscription-id: ${{ vars.PROD_AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Instance resource group
        id: instance-resource-group
        uses: ./github-actions/resource-group
        with:
          resource-group-name: ${{ env.resource-group-name }}
          resource-group-location: australiaeast
      - name: Instance log analytics
        id: instance-log-analytics
        uses: ./github-actions/log-analytics
        with:
          resource-group-name: ${{ env.resource-group-name }}
          resource-prefix: ${{ env.resource-prefix }}
          retention-in-days: ${{ startsWith(inputs.instance, 'sandbox.') && 30 || 180 }}
      - name: Instance SQL database
        id: instance-sql-db
        uses: ./github-actions/sql-db
        with:
          resource-prefix: ${{ env.resource-prefix }}
          sql-server-name: ${{ vars.SQL_SERVER_NAME }}
          elastic-pool-name: ${{ vars.SQL_ELASTIC_POOL_NAME }}
      - name: Deploy instance
        id: deploy-instance
        uses: ./github-actions/instance
        with:
          instance: ${{ inputs.instance }}
          node-env: production
          audit-log-streaming-enabled: ${{ vars.AUDIT_LOG_STREAMING_ENABLED }}
          app-insights-retention-in-days: ${{ startsWith(inputs.instance, 'sandbox.') && 30 || 180 }}
          dev-tools-enabled: ${{ vars.DEV_TOOLS_ENABLED }}
          face-check-enabled: ${{ vars.FACE_CHECK_ENABLED }}
          demo-enabled: ${{ vars.DEMO_ENABLED  }}
          mdoc-enabled: ${{ vars.MDOC_ENABLED }}
          identity-issuers: "${{ vars.IDENTITY_ISSUERS }}"
          platform-consumer-apps: "${{ vars.PLATFORM_CONSUMER_APPS }}"

          azure-client-id: ${{ vars.PROD_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ vars.PROD_AZURE_TENANT_ID }}
          azure-subscription-id: ${{ vars.PROD_AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ env.resource-group-name }}
          resource-group-unique-string: ${{ steps.instance-resource-group.outputs.resource-group-unique-string }}
          resource-prefix: ${{ env.resource-prefix }}
          deployment-service-principal-object-id: ${{ vars.PROD_AZURE_SERVICE_PRINCIPAL_OBJECT_ID }}
          vnet-name: ${{ vars.PROD_VNET_NAME }}
          platform-management-service-principal-object-id: ${{ vars.PROD_PLATFORM_MANAGEMENT_SERVICE_PRINCIPAL_OBJECT_ID }}

          key-vault-resource-group-name: ${{ vars.PROD_KEY_VAULT_RESOURCE_GROUP_NAME }}
          key-vault-name: ${{ vars.PROD_KEY_VAULT_NAME }}
          dns-api-key: ${{ secrets.PROD_DNS_API_KEY }}
          dns-api-secret: ${{ secrets.PROD_DNS_API_SECRET }}

          organisation-name: ${{ vars.VID_AUTHORITY_NAME }}
          organisation-domain: ${{ vars.VID_AUTHORITY_DOMAIN }}

          sql-server-name: ${{ vars.SQL_SERVER_NAME }}
          shared-resource-group-name: vo-platform-shared-infra
          shared-action-group-alert-name: vo-alerts
          app-service-plan-id: ${{ vars.APP_SERVICE_PLAN_ID }}
          app-service-zone-redundant: true
          redis-cache-sku: ${{ startsWith(inputs.instance, 'sandbox.') && 'Basic' || 'Standard' }}
          redis-cache-family: C
          redis-cache-capacity: ${{ startsWith(inputs.instance, 'sandbox.') && 0 || 1 }}

          cors-origin: "${{ vars.CORS_ORIGIN }}"

          sms-secret: ${{ secrets.PROD_SMS_SECRET }}
          sms-primary-token: ${{ secrets.PROD_SMS_PRIMARY_TOKEN }}
          email-api-key: ${{ secrets.PROD_EMAIL_API_KEY }}
          email-webhook-forwarder-secret: ${{ secrets.PROD_EMAIL_WEBHOOK_FORWARDER_SECRET }}

          internal-client-secret: ${{ secrets.PROD_INTERNAL_CLIENT_SECRET }}
          vid-callback-client-secret: ${{ secrets.PROD_VID_CALLBACK_CLIENT_SECRET }}

          limited-access-client-secret: ${{ secrets.PROD_LIMITED_ACCESS_CLIENT_SECRET }}
          limited-approval-client-secret: ${{ secrets.PROD_LIMITED_APPROVAL_CLIENT_SECRET }}
          limited-photo-capture-client-secret: ${{ secrets.PROD_LIMITED_PHOTO_CAPTURE_CLIENT_SECRET }}
          limited-async-issuance-client-secret: ${{ secrets.PROD_LIMITED_ASYNC_ISSUANCE_CLIENT_SECRET }}
          limited-demo-client-secret: ${{ secrets.PROD_LIMITED_DEMO_CLIENT_SECRET }}
          limited-oidc-client-secret: ${{ secrets.PROD_LIMITED_OIDC_CLIENT_SECRET }}

          home-tenant-id: ${{ vars.HOME_TENANT_ID }}
          home-tenant-name: ${{ vars.HOME_TENANT_NAME }}
          home-tenant-graph-client-id: ${{ vars.HOME_TENANT_GRAPH_CLIENT_ID }}
          home-tenant-graph-client-secret: ${{ secrets.HOME_TENANT_GRAPH_CLIENT_SECRET }}
          home-tenant-authority-id: ${{ vars.HOME_TENANT_AUTHORITY_ID }}
          home-tenant-vid-service-client-id: ${{ vars.HOME_TENANT_VID_SERVICE_CLIENT_ID }}
          home-tenant-vid-service-client-secret: ${{ secrets.HOME_TENANT_VID_SERVICE_CLIENT_SECRET }}
          additional-auth-tenant-ids: "${{ vars.ADDITIONAL_AUTH_TENANT_IDS }}"

          graphql-max-aliases: ${{ vars.GRAPHQL_MAX_ALIASES }}
          graphql-max-depth: ${{ vars.GRAPHQL_MAX_DEPTH }}
          graphql-max-directives: ${{ vars.GRAPHQL_MAX_DIRECTIVES }}
          graphql-max-tokens: ${{ vars.GRAPHQL_MAX_TOKENS }}

          log-level: ${{ vars.LOG_LEVEL }}
      - name: Instance SQL database audit
        id: instance-sql-db-audit
        uses: ./github-actions/sql-db-audit
        with:
          resource-group-name: vo-platform-shared-infra
          resource-prefix: ${{ env.resource-prefix }}
          sql-server-name: ${{ vars.SQL_SERVER_NAME }}
          log-analytics-id: ${{ steps.instance-log-analytics.outputs.log-analytics-id }}
