name: Destroy instance (non prod)
# DO NOT CHANGE THE FORMAT OF THE `run-name` FIELD
# - it follows a standard pattern across all components
# - it is used to derive the instance and environment
run-name: Destroy ${{ inputs.instance }} in non-prod

on:
  workflow_dispatch:
    inputs:
      instance:
        description: 'The instance to 💥💣💀DESTROY💀💣💥'
        required: true

concurrency:
  group: ${{ inputs.instance }}
  cancel-in-progress: true

jobs:

  destroy-instance:
    name: Destroy Instance
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: ${{ inputs.instance }}

    steps:
      - name: Set variables
        id: set-vars
        shell: bash
        run: |
          instance=${{ inputs.instance }}
          echo "instance=${instance}" >> $GITHUB_ENV
          echo "resource-group-name=vo-${instance/./-}-instance" >> $GITHUB_ENV
          echo "resource-prefix=vo-${instance/./-}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Destroy instance
        id: destroy-instance
        uses: ./.github/actions/destroy-instance
        with:
          azure-client-id: ${{ vars.NON_PROD_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ vars.NON_PROD_AZURE_TENANT_ID }}
          azure-subscription-id: ${{ vars.NON_PROD_AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ env.resource-group-name }}
          resource-prefix: ${{ env.resource-prefix }}

          instance: ${{ env.instance }}
          organisation-name: ${{ vars.VID_AUTHORITY_NAME }}
          organisation-domain: ${{ vars.VID_AUTHORITY_DOMAIN }}
          home-tenant-authority-id: ${{ vars.HOME_TENANT_AUTHORITY_ID }}

          dns-api-key: ${{ secrets.PROD_DNS_API_KEY }}
          dns-api-secret: ${{ secrets.PROD_DNS_API_SECRET }}

          sql-server-name: ${{ vars.SQL_SERVER_NAME }}
          shared-resource-group-name: vo-nonprd-platform-shared-infra
