name: Pull Request

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:

  ci-api:
    name: CI API
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 18.x
      pre-test-script: npm run test:ci:start-db
      test-script: npm run test:ci

  ci-migrations-function:
    name: CI Migrations Function
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 18.x
      working-directory: ./migrate-db-function
