name: Pull Request

on:
  pull_request:
    branches:
      - main
      - "feature/**"

permissions:
  contents: read
  checks: write
  pull-requests: read

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      docs_site: ${{ steps.filter.outputs.docs_site }}
      migrate_db: ${{ steps.filter.outputs.migrate_db }}
    steps:
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docs_site:
              - 'docs-site/**'
            migrate_db:
              - 'migrate-db/**'

  ci-api:
    name: CI API
    uses: ./.github/workflows/node-ci.yml
    with:
      node-version: 22.x
      audit-script: npm run audit
      run-audit: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
      pre-test-script: npm run test:ci:start-db
      test-script: npm run test:ci
      output-test-results: true

  ci-migrations-package:
    name: CI Migrations Package
    needs: changes
    if: needs.changes.outputs.migrate_db == 'true'
    uses: ./.github/workflows/node-ci.yml
    with:
      node-version: 22.x
      audit-script: npm run audit
      pre-run-script: npm ci --prefix ..
      pre-test-script: npm run test:ci:start-db --prefix ..
      run-audit: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
      working-directory: ./migrate-db
      test-script: npm run verify-migrations

  ci-docs-site:
    name: CI Docs Site
    needs: changes
    if: needs.changes.outputs.docs_site == 'true'
    uses: ./.github/workflows/node-ci.yml
    with:
      node-version: 22.x
      audit-script: npm run audit
      run-audit: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
      working-directory: ./docs-site
      run-build: true
      build-script: npm run build:pr
