name: Pull Request

on:
  pull_request:
    branches:
      - main
      - "feature/**"

permissions:
  contents: read
  checks: write

jobs:
  ci-api:
    name: CI API
    uses: ./.github/workflows/node-ci.yml
    with:
      noop: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      node-version: 22.x
      audit-script: npm run audit
      pre-test-script: npm run test:ci:start-db
      test-script: npm run test:ci
      output-test-results: true

  ci-migrations-package:
    name: CI Migrations Package
    uses: ./.github/workflows/node-ci.yml
    with:
      noop: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      node-version: 22.x
      audit-script: npm run audit
      working-directory: ./migrate-db

  ci-docs-site:
    name: CI Docs Site
    uses: ./.github/workflows/node-ci.yml
    with:
      noop: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      node-version: 22.x
      audit-script: npm run audit
      working-directory: ./docs-site
      run-build: true
      build-script: npm run build:pr

  