name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  ci-api:
    name: CI API
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 18.x
      pre-test-script: npm run test:ci:start-db
      test-script: npm run test:ci

  ci-migrations-function:
    name: CI Migrations Function
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 18.x
      working-directory: ./migrate-db-function

  build-api:
    name: Build API
    needs:
      - ci-api
    uses: makerxstudio/shared-config/.github/workflows/node-build-zip.yml@main
    with:
      node-version: 18.x
      artifact-name: api

  build-migrations-function:
    name: Build Migrations Function
    needs:
      - ci-migrations-function
    uses: makerxstudio/shared-config/.github/workflows/node-build-zip.yml@main
    with:
      node-version: 18.x
      working-directory: ./migrate-db-function
      artifact-name: migrations-function

  upload-other-artifacts:
    name: Upload other artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Upload infrastructure artifact
        uses: actions/upload-artifact@v3
        with:
          name: infrastructure
          path: ./infrastructure
          if-no-files-found: error

      - name: Upload github-actions artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-actions
          path: ./.github/actions
          if-no-files-found: error

  deploy-to-dev:
    name: Deploy to development environment
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: ${{ steps.deploy.outputs.api-url }}
    concurrency: deploy-to-dev
    needs:
      - build-api
      - build-migrations-function
      - upload-other-artifacts
    permissions:
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Deploy
        id: deploy
        uses: ./github-actions/deployment
        with:
          azure-client-id: ${{ vars.AZURE_CLIENT_ID }}
          azure-service-principal-object-id: ${{ vars.AZURE_SERVICE_PRINCIPAL_OBJECT_ID }}
          azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          environment: dev
          resource-group-name: vo-dev-verified-orchestration
          sql-instance-name: vo-dev-verified-orchestration-sql
          sql-instance-aad-administrator-name: Verified Orchestration SQL Administrators (dev)
          sql-instance-aad-administrator-object-id: cb26d064-654b-49d4-a96c-f296e3667a55
          sql-database-sku: S1
          redis-cache-name: vo-dev-verified-orchestration-redis
          redis-cache-sku: Basic
          redis-cache-family: C
          redis-cache-capacity: 1
          app-service-plan-sku: B2
          api-app-service-name: vo-dev-verified-orchestration-api
          migrations-function-app-name: vo-dev-verified-orchestration-migrations
          migrations-app-client-id: a705473f-45d1-498a-a9aa-c767c4d406b8
          api-cookie-secret: ${{ secrets.API_COOKIE_SECRET }}
          api-client-secret: ${{ secrets.API_CLIENT_SECRET }}
          ui-client-secret: ${{ secrets.UI_CLIENT_SECRET }}
          b2c-graph-client-secret: ${{ secrets.B2C_GRAPH_CLIENT_SECRET }}
          vid-callback-client-secret: ${{ secrets.VID_CALLBACK_CLIENT_SECRET }}
          sendgrid-api-key: ${{ secrets.SENDGRID_API_KEY }}
