name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  ci-api:
    name: CI API
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: '18.x'
    secrets:
      npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}

  # ci-infrastructure:
  #   name: CI Infrastructure
  #   uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
  #   with:
  #     working-directory: ./infrastructure
