name: Shared infra (production)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-to-prod:
    name: Deploy shared infrastructure to the production environment
    runs-on: ubuntu-latest
    concurrency: deploy-to-prod
    environment:
      name: Production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Shared infrastructure resource group
        id: deploy-resource-group
        uses: ./.github/actions/resource-group
        with:
          azure-client-id: ${{ vars.PROD_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ vars.PROD_AZURE_TENANT_ID }}
          azure-subscription-id: ${{ vars.PROD_AZURE_SUBSCRIPTION_ID }}
          resource-group-name: vo-platform-shared-infra
          resource-group-location: australiaeast
      - name: Shared infrastructure
        id: deploy
        uses: ./.github/actions/shared-infra
        with:
          azure-client-id: ${{ vars.PROD_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ vars.PROD_AZURE_TENANT_ID }}
          azure-subscription-id: ${{ vars.PROD_AZURE_SUBSCRIPTION_ID }}
          infra-environment: prd
          resource-group-name: vo-platform-shared-infra
