name: Shared infra (non prod)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-to-non-prod:
    name: Deploy shared infrastructure to the non prod environment
    runs-on: ubuntu-latest
    concurrency: deploy-to-non-prod
    environment:
      name: Non-production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.NON_PROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.NON_PROD_AZURE_TENANT_ID }}
          subscription-id: ${{ vars.NON_PROD_AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Shared infrastructure resource group
        id: deploy-resource-group
        uses: ./.github/actions/resource-group
        with:
          resource-group-name: vo-nonprd-platform-shared-infra
          resource-group-location: australiaeast
      - name: Shared infrastructure
        id: deploy
        uses: ./.github/actions/shared-infra
        with:
          azure-client-id: ${{ vars.NON_PROD_AZURE_CLIENT_ID }}
          infra-environment: nonprd
          resource-group-name: vo-nonprd-platform-shared-infra
          partner-id: ${{ vars.NON_PROD_PARTNER_ID }}
